package com.briup.apps.poll.bean;

public class Clazz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.name
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.survey_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private Integer surveyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.student_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private Integer studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.grade_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private Long gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.charge_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private Long chargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_clazz.description
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.id
     *
     * @return the value of poll_clazz.id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.id
     *
     * @param id the value for poll_clazz.id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.name
     *
     * @return the value of poll_clazz.name
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.name
     *
     * @param name the value for poll_clazz.name
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.survey_number
     *
     * @return the value of poll_clazz.survey_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public Integer getSurveyNumber() {
        return surveyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.survey_number
     *
     * @param surveyNumber the value for poll_clazz.survey_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setSurveyNumber(Integer surveyNumber) {
        this.surveyNumber = surveyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.student_number
     *
     * @return the value of poll_clazz.student_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.student_number
     *
     * @param studentNumber the value for poll_clazz.student_number
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.grade_id
     *
     * @return the value of poll_clazz.grade_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.grade_id
     *
     * @param gradeId the value for poll_clazz.grade_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.charge_id
     *
     * @return the value of poll_clazz.charge_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public Long getChargeId() {
        return chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.charge_id
     *
     * @param chargeId the value for poll_clazz.charge_id
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setChargeId(Long chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_clazz.description
     *
     * @return the value of poll_clazz.description
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_clazz.description
     *
     * @param description the value for poll_clazz.description
     *
     * @mbg.generated Wed Nov 14 11:00:07 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}