package com.briup.apps.poll.bean;

import java.util.Date;

public class PollUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.id
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.username
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.nickname
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.password
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.enabled
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.email
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.userface
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String userface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.regTime
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private Date regtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_user.gender
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.id
     *
     * @return the value of poll_user.id
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.id
     *
     * @param id the value for poll_user.id
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.username
     *
     * @return the value of poll_user.username
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.username
     *
     * @param username the value for poll_user.username
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.nickname
     *
     * @return the value of poll_user.nickname
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.nickname
     *
     * @param nickname the value for poll_user.nickname
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.password
     *
     * @return the value of poll_user.password
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.password
     *
     * @param password the value for poll_user.password
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.enabled
     *
     * @return the value of poll_user.enabled
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.enabled
     *
     * @param enabled the value for poll_user.enabled
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.email
     *
     * @return the value of poll_user.email
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.email
     *
     * @param email the value for poll_user.email
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.userface
     *
     * @return the value of poll_user.userface
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getUserface() {
        return userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.userface
     *
     * @param userface the value for poll_user.userface
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setUserface(String userface) {
        this.userface = userface == null ? null : userface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.regTime
     *
     * @return the value of poll_user.regTime
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.regTime
     *
     * @param regtime the value for poll_user.regTime
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_user.gender
     *
     * @return the value of poll_user.gender
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_user.gender
     *
     * @param gender the value for poll_user.gender
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }
}