package com.briup.apps.poll.dao;

import com.briup.apps.poll.bean.PollUser;
import com.briup.apps.poll.bean.PollUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    long countByExample(PollUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int deleteByExample(PollUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int insert(PollUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int insertSelective(PollUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    List<PollUser> selectByExample(PollUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    PollUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") PollUser record, @Param("example") PollUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int updateByExample(@Param("record") PollUser record, @Param("example") PollUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int updateByPrimaryKeySelective(PollUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_user
     *
     * @mbg.generated Wed Nov 14 16:34:00 CST 2018
     */
    int updateByPrimaryKey(PollUser record);
}