package com.briup.apps.poll.dao;

import com.briup.apps.poll.bean.SurveyLog;
import com.briup.apps.poll.bean.SurveyLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    long countByExample(SurveyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int deleteByExample(SurveyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int insert(SurveyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int insertSelective(SurveyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    List<SurveyLog> selectByExample(SurveyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    SurveyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") SurveyLog record, @Param("example") SurveyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int updateByExample(@Param("record") SurveyLog record, @Param("example") SurveyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int updateByPrimaryKeySelective(SurveyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey_log
     *
     * @mbg.generated Fri Nov 16 10:06:41 CST 2018
     */
    int updateByPrimaryKey(SurveyLog record);
}